package com.wasmo.db

import wasmo.sql.SqlConnection

val CURRENT_SCHEMA_VERSION: Long = 1L

suspend fun SqlConnection.migrate(
  oldVersion: Long = 0L,
  newVersion: Long = CURRENT_SCHEMA_VERSION,
) {
  if (oldVersion < 1 && newVersion >= 1) {
    // Computer.
    execute(
      """
      CREATE TABLE Computer (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ NOT NULL,
        version BIGINT NOT NULL,
        slug VARCHAR(255) NOT NULL
      )
      """,
    )
    execute(
      """
      CREATE UNIQUE INDEX ComputerSlug ON Computer (
        slug
      )
      """,
    )

    // InstalledApp.
    execute(
      """
      CREATE TABLE InstalledApp (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        installed_at TIMESTAMPTZ NOT NULL,
        computer_id BIGINT NOT NULL,
        slug VARCHAR(255) NOT NULL,
        active BOOLEAN NULL,
        version BIGINT NOT NULL,
        wasmo_file_address VARCHAR(65535) NOT NULL,
        active_release_id BIGINT NULL DEFAULT NULL
      )
      """,
    )
    execute(
      """
      CREATE UNIQUE INDEX InstalledAppComputerIdSlugActive ON InstalledApp (
        computer_id,
        slug,
        active
      ) WHERE active IS NOT NULL
      """,
    )

    // Account.
    execute(
      """
      CREATE TABLE Account (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        version INTEGER NOT NULL
      )
      """,
    )

    // Cookie
    execute(
      """
      CREATE TABLE Cookie (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ NOT NULL,
        account_id BIGINT NOT NULL,
        token VARCHAR(25) UNIQUE NOT NULL,
        created_by_user_agent VARCHAR(255) NULL,
        created_by_ip VARCHAR(255) NULL
      )
      """,
    )
    execute(
      """
      CREATE INDEX CookieByAccountId ON Cookie (
        account_id
      )
      """,
    )

    // Passkey.
    execute(
      """
      CREATE TABLE Passkey (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ NOT NULL,
        account_id BIGINT NOT NULL,
        passkey_id VARCHAR(255) UNIQUE NOT NULL,
        aaguid VARCHAR(36) NOT NULL,
        created_by_user_agent VARCHAR(255) NULL,
        created_by_ip VARCHAR(255) NULL,
        registration_record VARCHAR(65535) NOT NULL
      )
      """,
    )
    execute(
      """
      CREATE INDEX PasskeyByAccountId ON Passkey (
        account_id
      )
      """,
    )

    // Invite.
    execute(
      """
      CREATE TABLE Invite (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ NOT NULL,
        created_by BIGINT NOT NULL,
        version INTEGER NOT NULL,
        code VARCHAR(25) UNIQUE NOT NULL,
        claimed_at TIMESTAMPTZ NULL,
        claimed_by BIGINT NULL
      )
      """,
    )
    execute(
      """
      CREATE INDEX InviteByClaimedById ON Invite (
        claimed_by
      )
      """,
    )

    // StripeCustomer.
    execute(
      """
      CREATE TABLE StripeCustomer (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ NOT NULL,
        version INTEGER NOT NULL,
        stripe_customer_id VARCHAR(255) UNIQUE NOT NULL,
        name VARCHAR(65535) NOT NULL,
        email VARCHAR(65535) NOT NULL,
        country VARCHAR(255) NOT NULL,
        postal_code VARCHAR(255) NOT NULL
      )
      """,
    )

    // ComputerAllocation.
    execute(
      """
      CREATE TABLE ComputerAllocation (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ NOT NULL,
        version INTEGER NOT NULL,
        stripe_customer_id BIGINT NOT NULL,
        stripe_subscription_id VARCHAR(255) NOT NULL,
        computer_id BIGINT NOT NULL,
        active_start TIMESTAMPTZ NOT NULL,
        active_end TIMESTAMPTZ NOT NULL
      )
      """,
    )
    execute(
      """
      CREATE INDEX ComputerAllocationByStripeSubscriptionIdActiveStart ON ComputerAllocation (
        stripe_subscription_id,
        active_start
      )
      """,
    )
    execute(
      """
      CREATE INDEX ComputerAllocationByComputerIdActiveStart ON ComputerAllocation (
        computer_id,
        active_start
      )
      """,
    )

    // ComputerSpec.
    execute(
      """
      CREATE TABLE ComputerSpec (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ NOT NULL,
        version BIGINT NOT NULL,
        account_id BIGINT NOT NULL,
        token VARCHAR(25) UNIQUE NOT NULL,
        slug VARCHAR(255) NOT NULL,
        computer_id BIGINT NULL
      )
      """,
    )

    // ComputerAccess.
    execute(
      """
      CREATE TABLE ComputerAccess (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at TIMESTAMPTZ NOT NULL,
        version INTEGER NOT NULL,
        computer_id BIGINT NOT NULL,
        account_id BIGINT NOT NULL
      )
      """,
    )
    execute(
      """
      CREATE INDEX ComputerAccessByComputerIdAccountId ON ComputerAccess (
        computer_id,
        account_id
      )
      """,
    )
    execute(
      """
      CREATE INDEX ComputerAccessByAccountIdComputerId ON ComputerAccess (
        account_id,
        computer_id
      )
      """,
    )

    // InstalledAppRelease.
    execute(
      """
      CREATE TABLE InstalledAppRelease (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        first_active_at TIMESTAMPTZ NOT NULL,
        computer_id BIGINT NOT NULL,
        installed_app_id BIGINT NOT NULL,
        app_version BIGINT NOT NULL,
        app_manifest_data VARCHAR(65535) NOT NULL
      )
      """,
    )
    execute(
      """
      CREATE INDEX InstalledAppReleaseComputerIdInstalledAppId ON InstalledAppRelease (
        computer_id,
        installed_app_id
      )
      """,
    )
  }
}
