target = 'https://wasmo.com/sdk/1'
version = 1
slug = 'zap'

[[resource]]
url = 'assets/maskable-icon.svg'

[[route]]
path = '/assets/maskable-icon.svg'
resource_path = '/assets/maskable-icon.svg'

[launcher]
label = 'Zap'
maskable_icon_path = '/assets/maskable-icon.svg'
