plugins {
  alias(libs.plugins.kotlin.multiplatform)
  alias(libs.plugins.metro)
  id("wasmo-build")
}

wasmoBuild {
  libraryJvm()
}

kotlin {
  sourceSets {
    val jvmMain by getting {
      dependencies {
        implementation(libs.commons.dbcp2)
        implementation(libs.kotlinx.html)
        implementation(libs.kotlinx.io)
        implementation(libs.kotlinx.io.okio)
        implementation(libs.kotlinx.serialization.json)
        implementation(libs.ktor.server.call.logging)
        implementation(libs.ktor.server.config.yaml)
        implementation(libs.ktor.server.core)
        implementation(libs.ktor.server.default.headers)
        implementation(libs.ktor.server.host.common)
        implementation(libs.ktor.server.html.builder)
        implementation(libs.ktor.server.netty)
        implementation(libs.ktor.server.websockets)
        implementation(libs.logback.classic)
        implementation(libs.okhttp)
        implementation(libs.okio)
        implementation(libs.stripe)
        implementation(libs.vertx.postgresql)
        implementation(project(":apps:journal:wasmo-app"))
        implementation(project(":identifiers"))
        implementation(project(":os:api"))
        implementation(project(":os:catalog"))
        implementation(project(":os:client:app"))
        implementation(project(":os:framework"))
        implementation(project(":os:logging"))
        implementation(project(":os:routes"))
        implementation(project(":os:server:accounts:api"))
        implementation(project(":os:server:accounts:real"))
        implementation(project(":os:server:calls:api"))
        implementation(project(":os:server:calls:real"))
        implementation(project(":os:server:computers:api"))
        implementation(project(":os:server:computers:real"))
        implementation(project(":os:server:db"))
        implementation(project(":os:server:deployment"))
        implementation(project(":os:server:emails:real"))
        implementation(project(":os:server:events:api"))
        implementation(project(":os:server:events:logging"))
        implementation(project(":os:server:identifiers"))
        implementation(project(":os:server:installedapps:api"))
        implementation(project(":os:server:installedapps:real"))
        implementation(project(":os:server:jobs:absurd"))
        implementation(project(":os:server:jobs:api"))
        implementation(project(":os:server:objectstore:api"))
        implementation(project(":os:server:objectstore:fs"))
        implementation(project(":os:server:objectstore:s3"))
        implementation(project(":os:server:okhttpclient"))
        implementation(project(":os:server:passkeys:api"))
        implementation(project(":os:server:passkeys:real"))
        implementation(project(":os:server:payments:api"))
        implementation(project(":os:server:payments:stripe"))
        implementation(project(":os:server:permits:api"))
        implementation(project(":os:server:permits:real"))
        implementation(project(":os:server:sendemail:api"))
        implementation(project(":os:server:sendemail:postmark"))
        implementation(project(":os:server:sql:api"))
        implementation(project(":os:server:sql:real"))
        implementation(project(":os:server:wasm:api"))
        implementation(project(":os:server:wasm:jvm"))
        implementation(project(":os:server:website:api"))
        implementation(project(":os:server:website:real"))
        implementation(project(":platform:api"))
        implementation(project(":platform:packaging"))
        implementation(project(":support:issues"))
        implementation(project(":support:tokens"))
      }
    }
  }
}
