plugins {
  alias(libs.plugins.kotlin.multiplatform)
  alias(libs.plugins.metro)
  id("wasmo-build")
}

wasmoBuild {
  libraryJvm()
}

kotlin {
  sourceSets {
    val jvmMain by getting {
      dependencies {
        implementation(libs.commons.dbcp2)
        implementation(libs.kotlinx.html)
        implementation(libs.kotlinx.io)
        implementation(libs.kotlinx.io.okio)
        implementation(libs.kotlinx.serialization.json)
        implementation(libs.ktor.server.call.logging)
        implementation(libs.ktor.server.config.yaml)
        implementation(libs.ktor.server.core)
        implementation(libs.ktor.server.default.headers)
        implementation(libs.ktor.server.host.common)
        implementation(libs.ktor.server.html.builder)
        implementation(libs.ktor.server.netty)
        implementation(libs.ktor.server.websockets)
        implementation(libs.logback.classic)
        implementation(libs.okhttp)
        implementation(libs.okio)
        implementation(libs.stripe)
        implementation(libs.vertx.postgresql)
        implementation(projects.apps.journal.wasmoApp)
        implementation(projects.identifiers)
        implementation(projects.os.api)
        implementation(projects.os.catalog)
        implementation(projects.os.client.app)
        implementation(projects.os.framework)
        implementation(projects.os.logging)
        implementation(projects.os.routes)
        implementation(projects.os.server.accounts.api)
        implementation(projects.os.server.accounts.real)
        implementation(projects.os.server.calls.api)
        implementation(projects.os.server.calls.real)
        implementation(projects.os.server.computers.api)
        implementation(projects.os.server.computers.real)
        implementation(projects.os.server.db)
        implementation(projects.os.server.emails.real)
        implementation(projects.os.server.events.api)
        implementation(projects.os.server.events.logging)
        implementation(projects.os.server.identifiers)
        implementation(projects.os.server.installedapps.api)
        implementation(projects.os.server.installedapps.real)
        implementation(projects.os.server.jobs.absurd)
        implementation(projects.os.server.jobs.api)
        implementation(projects.os.server.objectstore.api)
        implementation(projects.os.server.objectstore.fs)
        implementation(projects.os.server.objectstore.s3)
        implementation(projects.os.server.okhttpclient)
        implementation(projects.os.server.passkeys.api)
        implementation(projects.os.server.passkeys.real)
        implementation(projects.os.server.payments.api)
        implementation(projects.os.server.payments.stripe)
        implementation(projects.os.server.permits.api)
        implementation(projects.os.server.permits.real)
        implementation(projects.os.server.sendemail.api)
        implementation(projects.os.server.sendemail.postmark)
        implementation(projects.os.server.sql.api)
        implementation(projects.os.server.sql.real)
        implementation(projects.os.server.wasm.api)
        implementation(projects.os.server.wasm.jvm)
        implementation(projects.os.server.website.api)
        implementation(projects.os.server.website.real)
        implementation(projects.platform.api)
        implementation(projects.platform.packaging)
        implementation(projects.support.issues)
        implementation(projects.support.tokens)
      }
    }
  }
}
