@file:OptIn(ExperimentalUuidApi::class)

package com.wasmo.sql.vertx

import kotlin.time.Instant
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import okio.ByteString
import wasmo.json.JsonLiteral
import wasmo.sql.SqlConnection

data class AllTypes(
  val valueBool: Boolean? = null,
  val valueS32: Int? = null,
  val valueS64: Long? = null,
  val valueF32: Float? = null,
  val valueF64: Double? = null,
  val valueInstant: Instant? = null,
  val valueString: String? = null,
  val valueBytes: ByteString? = null,
  val valueUuid: Uuid? = null,
  val valueJson: JsonLiteral? = null,
)

suspend fun SqlConnection.createTableAllTypes() {
  execute(
    """
    CREATE TABLE AllTypes (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      value_bool BOOLEAN,
      value_s32 INTEGER,
      value_s64 BIGINT,
      value_f32 REAL,
      value_f64 DOUBLE PRECISION,
      value_instant TIMESTAMPTZ,
      value_string TEXT,
      value_bytes BYTEA,
      value_uuid UUID,
      value_json JSONB
    )
    """,
  )
}

suspend fun SqlConnection.insertIntoAllTypes(value: AllTypes) {
  execute(
    """
    INSERT INTO AllTypes (
      value_bool, value_s32, value_s64, value_f32, value_f64,
      value_instant, value_string, value_bytes, value_uuid, value_json
    ) VALUES (
      $1, $2, $3, $4, $5,
      $6, $7, $8, $9, $10
    )
    """,
  ) {
    bindBool(0, value.valueBool)
    bindS32(1, value.valueS32)
    bindS64(2, value.valueS64)
    bindF32(3, value.valueF32)
    bindF64(4, value.valueF64)
    bindInstant(5, value.valueInstant)
    bindString(6, value.valueString)
    bindBytes(7, value.valueBytes)
    bindUuid(8, value.valueUuid)
    bindJson(9, value.valueJson)
  }
}

suspend fun SqlConnection.selectFromAllTypes(): List<AllTypes> {
  return buildList {
    executeQuery(
      """
      SELECT
        value_bool, value_s32, value_s64, value_f32, value_f64,
        value_instant, value_string, value_bytes, value_uuid, value_json
      FROM AllTypes
      """,
    ) {
    }.use { rowIterator ->
      while (true) {
        val row = rowIterator.next() ?: break
        add(
          AllTypes(
            valueBool = row.getBool(0),
            valueS32 = row.getS32(1),
            valueS64 = row.getS64(2),
            valueF32 = row.getF32(3),
            valueF64 = row.getF64(4),
            valueInstant = row.getInstant(5),
            valueString = row.getString(6),
            valueBytes = row.getBytes(7),
            valueUuid = row.getUuid(8),
            valueJson = row.getJson(9),
          ),
        )
      }
    }
  }
}
