# Suppress a warning about using @Language in Kotlin/JS
#   w: Unsupported `compileOnly` Dependencies in Kotlin Targets
#   A compileOnly dependency is used in targets: Kotlin/JS.
kotlin.suppressGradlePluginWarnings=IncorrectCompileOnlyDependencyWarning
# We build all client apps concurrently and that requires a lot of memory.
kotlin.daemon.jvmargs=-Xms4G -Xmx4G
org.gradle.jvmargs=-Xms1G -Xmx1G
org.gradle.parallel=true
