plugins {
  alias(libs.plugins.kotlin.multiplatform)
  alias(libs.plugins.kotlin.serialization)
  alias(libs.plugins.burst)
  alias(libs.plugins.metro)
  id("wasmo-build")
}

wasmoBuild {
  libraryJvm()
}

kotlin {
  sourceSets {
    val jvmMain by getting {
      dependencies {
        implementation(libs.burst.coroutines)
        implementation(libs.commons.dbcp2)
        implementation(libs.kotlinx.coroutines.core)
        implementation(libs.kotlinx.coroutines.reactive)
        implementation(libs.kotlinx.coroutines.test)
        implementation(libs.kotlinx.serialization.core)
        implementation(libs.kotlinx.serialization.json)
        implementation(libs.okhttp)
        implementation(libs.okio)
        implementation(libs.okio.fakefilesystem)
        implementation(libs.postgresql)
        implementation(libs.tomlkt)
        implementation(libs.vertx.postgresql)
        implementation(libs.vertx.sql.client)
        implementation(libs.webauthn4j.core)
        implementation(projects.identifiers)
        implementation(projects.os.api)
        implementation(projects.os.framework)
        implementation(projects.os.routes)
        implementation(projects.os.server.accounts.api)
        implementation(projects.os.server.accounts.real)
        implementation(projects.os.server.calls.api)
        implementation(projects.os.server.calls.real)
        implementation(projects.os.server.computers.api)
        implementation(projects.os.server.computers.real)
        implementation(projects.os.server.db)
        implementation(projects.os.server.emails.real)
        implementation(projects.os.server.events.api)
        implementation(projects.os.server.identifiers)
        implementation(projects.os.server.installedapps.api)
        implementation(projects.os.server.installedapps.real)
        implementation(projects.os.server.jobs.absurd)
        implementation(projects.os.server.jobs.api)
        implementation(projects.os.server.objectstore.api)
        implementation(projects.os.server.objectstore.fs)
        implementation(projects.os.server.passkeys.api)
        implementation(projects.os.server.passkeys.real)
        implementation(projects.os.server.payments.api)
        implementation(projects.os.server.payments.stripe)
        implementation(projects.os.server.permits.api)
        implementation(projects.os.server.permits.real)
        implementation(projects.os.server.sendemail.api)
        implementation(projects.os.server.sql.api)
        implementation(projects.os.server.sql.real)
        implementation(projects.os.server.sql.testing)
        implementation(projects.os.server.wasm.api)
        implementation(projects.os.server.wasm.jvm)
        implementation(projects.os.server.website.api)
        implementation(projects.os.server.website.real)
        implementation(projects.platform.api)
        implementation(projects.platform.packaging)
        implementation(projects.platform.testing)
        implementation(projects.support.absurd)
        implementation(projects.support.tokens)
        implementation(projects.wasmox.wasmoxSql)
      }
    }
  }
}
