CREATE TABLE Password (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL,
  account_id BIGINT UNIQUE NOT NULL, /* TODO: Decide whether or not account_id should be UNIQUE. */
  username VARCHAR(255) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NULL,
  created_by_user_agent VARCHAR(255) NULL,
  created_by_ip VARCHAR(255) NULL,
  active BOOLEAN NOT NULL
);

CREATE INDEX PasswordByAccountId ON Password (
  account_id
);
