CREATE TABLE LinkedEmailAddress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL,
  account_id BIGINT NOT NULL,
  email_address VARCHAR(255) UNIQUE NOT NULL,
  active BOOLEAN NULL
);

CREATE UNIQUE INDEX LinkedEmailAddressEmailAddressActive ON LinkedEmailAddress (
  email_address,
  active
)
WHERE active IS NOT NULL;
