CREATE TABLE InstalledApp (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installed_at TIMESTAMPTZ NOT NULL,
  computer_id BIGINT NOT NULL,
  slug VARCHAR(255) NOT NULL,
  active BOOLEAN NULL,
  version BIGINT NOT NULL,
  wasmo_file_address VARCHAR(65535) NOT NULL,
  active_release_id BIGINT NULL DEFAULT NULL
);

CREATE UNIQUE INDEX InstalledAppComputerIdSlugActive ON InstalledApp (
  computer_id,
  slug,
  active
) WHERE active IS NOT NULL;