CREATE TABLE Permit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  value VARCHAR(255) NOT NULL,
  serial_number BIGINT,
  acquire_at TIMESTAMPTZ  NOT NULL
);

CREATE UNIQUE INDEX PermitTypeValueSerialNumber
ON Permit (
   type,
   value,
   serial_number
);
