CREATE TABLE ComputerAllocation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- 'stripe' or 'free'
  type VARCHAR(20) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  version INTEGER NOT NULL,
  stripe_customer_id BIGINT,
  stripe_subscription_id VARCHAR(255),
  computer_id BIGINT NOT NULL,
  active_start TIMESTAMPTZ NOT NULL,
  active_end TIMESTAMPTZ
);

CREATE INDEX ComputerAllocationByStripeSubscriptionIdActiveStart ON ComputerAllocation (
  stripe_subscription_id,
  active_start
) WHERE type = 'stripe';

CREATE INDEX ComputerAllocationByComputerIdActiveStart ON ComputerAllocation (
  computer_id,
  active_start
);
