CREATE TABLE InstalledAppDatabase (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  installed_app_id BIGINT NOT NULL,
  slug VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  version BIGINT NOT NULL,
  credential BYTEA NOT NULL
);

CREATE UNIQUE INDEX InstalledAppDatabaseInstalledAppIdSlug ON InstalledAppDatabase (
  installed_app_id,
  slug
);
