CREATE TABLE Cookie (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL,
  account_id BIGINT NOT NULL,
  token VARCHAR(25) UNIQUE NOT NULL,
  created_by_user_agent VARCHAR(255) NULL,
  created_by_ip VARCHAR(255) NULL
);

CREATE INDEX CookieByAccountId ON Cookie (
  account_id
);