CREATE TABLE ComputerAccess (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL,
  version INTEGER NOT NULL,
  computer_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL
);

CREATE INDEX ComputerAccessByComputerIdAccountId ON ComputerAccess (
  computer_id,
  account_id
);

CREATE INDEX ComputerAccessByAccountIdComputerId ON ComputerAccess (
  account_id,
  computer_id
);

CREATE UNIQUE INDEX ComputerAccessByComputerIdUserId ON ComputerAccess (
  computer_id,
  user_id
);
