CREATE TABLE SubscriptionPeriod (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL,
  version INTEGER NOT NULL,
  stripe_customer_id BIGINT NOT NULL,
  stripe_subscription_id VARCHAR(255) NOT NULL,
  computer_id BIGINT NOT NULL,
  active_start TIMESTAMPTZ NOT NULL,
  active_end TIMESTAMPTZ NOT NULL
);

CREATE INDEX SubscriptionPeriodByStripeSubscriptionIdActiveStart ON SubscriptionPeriod (
  stripe_subscription_id,
  active_start
);

CREATE INDEX SubscriptionPeriodByComputerIdActiveStart ON SubscriptionPeriod (
  computer_id,
  active_start
);
