CREATE TABLE Username (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL,
  -- 0 or 1 usernames per account. If this ever changes, need to drop 'UNIQUE' here and on the index.
  account_id BIGINT UNIQUE NOT NULL,
  username VARCHAR(255) UNIQUE NOT NULL
);

CREATE UNIQUE INDEX UsernameUsername ON Username(username);
CREATE UNIQUE INDEX UsernameAccountId ON Username(account_id);
