CREATE TABLE PasswordDigest (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL UNIQUE,
  -- Subject to clock limitations (e.g. may not be strictly increasing).
  created_at TIMESTAMPTZ NOT NULL,
  -- Includes raw hash, salt (but not pepper), and metadata such as hash algorithm version used.
  password_digest TEXT NOT NULL
);
