CREATE TABLE PasswordDigest (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id BIGINT NOT NULL UNIQUE,
  -- Subject to clock limitations (e.g. may not be strictly increasing).
  created_at TIMESTAMPTZ NOT NULL,
  password_digest TEXT NOT NULL
);
