package wasmo:platform;

/// The API contract between Wasmo OS and its applications.
@since(version = 0.1.0)
world wasmo {
  /// A limited environment with runtime configuration.
  import wasi:cli/environment@0.2.0;

  /// A developer-facing console.
  import wasi:cli/stderr@0.2.0;
  import wasi:cli/stdout@0.2.0;

  /// Stdin is present, but empty.
  import wasi:cli/stdin@0.2.0;

  /// Time.
  import wasi:clocks/monotonic-clock@0.2.0;
  import wasi:clocks/wall-clock@0.2.0;

  /// Randomness.
  import wasi:random/insecure-seed@0.2.0;
  import wasi:random/insecure@0.2.0;
  import wasi:random/random@0.2.0;

  /// HTTP inbound and outbound.
  import wasmo:http/http-service;
  export wasmo:http/http-service;

  // Object store.
  import wasmo:object-store/object-store;

  /// Job queue.
  import wasmo:jobs/job-queue-factory;
  export wasmo:jobs/job-handler-factory;

  /// SQL database.
  export wasmo:sql/sql-database-factory;

  /// Data transfer.
  export wasmo:transfer-service/transfer-service;

  /// Invoked after an app is first installed, and after each version update.
  export after-install: func(
    /// will be 0 if this is the first install of the app.
    old-version: s64,
    new-version: s64,
  );
}
