services:
  postgresql:
    image: postgres:18.1
    environment:
      POSTGRES_PASSWORD: password

  ci-build:
    image: wasmo/ci:latest
    working_dir: /workdir
    volumes:
      - ..:/workdir
      - home-gradle:/home/gradle/.gradle
      - workdir-gradle:/workdir/.gradle
    depends_on:
      - postgresql
    environment:
      - POSTGRESQL_HOSTNAME=postgresql
      - ORG_GRADLE_PROJECT_mavenCentralUsername
      - ORG_GRADLE_PROJECT_mavenCentralPassword
      - ORG_GRADLE_PROJECT_signingInMemoryKey

volumes:
  home-gradle:
  workdir-gradle:
