steps:
  - label: ":gradle: Test"
    command: "gradle jsTest jvmTest wasmWasiTest test compileKotlinJvm compileKotlinJs compileKotlinWasmWasi --continue"
    plugins:
      docker-compose#v3.8.0:
        run: gradle
        config: .buildkite/docker-compose.yml
