steps:
  - label: ":gradle: Test"
    command: "gradle jsTest jvmTest wasmWasiTest test compileKotlinJvm compileKotlinJs compileKotlinWasmWasi --continue"
    plugins:
      - docker#v3.5.0:
          image: "gradle:9.5.0-jdk21-alpine"
