steps:
  - label: ":gradle: Publish"
    commands:
      - "cat .buildkite/gradle.properties >> gradle.properties"
      - "gradle publishAndReleaseToMavenCentral"
    plugins:
      - docker-compose#v5.11.0:
          run: ci-build
          config: .buildkite/docker-compose.yml
          environment:
            - "ORG_GRADLE_PROJECT_mavenCentralUsername"
            - "ORG_GRADLE_PROJECT_mavenCentralPassword"
            - "ORG_GRADLE_PROJECT_signingInMemoryKey"
      - docker-login#v3.0.0:
          username: wasmo
          isolate-config: false
    secrets:
      ORG_GRADLE_PROJECT_mavenCentralUsername: SONATYPE_CENTRAL_USERNAME
      ORG_GRADLE_PROJECT_mavenCentralPassword: SONATYPE_CENTRAL_PASSWORD
      ORG_GRADLE_PROJECT_signingInMemoryKey: GPG_SECRET_KEY
      DOCKER_LOGIN_PASSWORD: DOCKER_LOGIN_PASSWORD
