CREATE TABLE InstalledAppRelease (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_active_at TIMESTAMPTZ NOT NULL,
  computer_id BIGINT NOT NULL,
  installed_app_id BIGINT NOT NULL,
  app_version BIGINT NOT NULL,
  app_manifest_data VARCHAR(65535) NOT NULL
);

CREATE INDEX InstalledAppReleaseComputerIdInstalledAppId ON InstalledAppRelease (
  computer_id,
  installed_app_id
);