package com.wasmo.support.wit.kotlin.generator

import com.squareup.kotlinpoet.BOOLEAN
import com.squareup.kotlinpoet.Documentable
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec

class ApiGenerator {
  fun generate(
    witPackage: KtWitPackage,
    worldFilter: (KtWorld) -> Boolean = { true },
  ): FileSpec {
    return FileSpec.builder(witPackage.packageName, "Api")
      .addFileComment("Generated by wit-kotlin-generator. Do not edit.")
      .apply {
        for (declaration in witPackage.items) {
          if (declaration is KtWorld && !worldFilter(declaration)) continue
          addPackageItem(declaration)
        }
      }
      .build()
  }

  private fun FileSpec.Builder.addPackageItem(value: KtWitPackage.Item) {
    when (value) {
      is KtInterface -> addType(generate(value))
      is KtWorld -> addType(generate(value))
    }
  }

  private fun <T : Documentable.Builder<*>> T.setDeclaration(
    declaration: KtDeclaration? = null,
  ): T = apply {
    val documentation = declaration?.documentation
    if (documentation != null) {
      addKdoc(documentation.trimIndent())
    }
  }

  private fun generate(value: KtInterface) = TypeSpec.interfaceBuilder(value.type.simpleName)
    .setDeclaration(value)
    .apply {
      for (declaration in value.items) {
        addInterfaceItem(declaration)
      }
    }
    .build()

  private fun TypeSpec.Builder.addInterfaceItem(value: KtInterface.Item) {
    when (value) {
      is KtEnum -> addType(generate(value))
      is KtFlags -> addType(generate(value))
      is KtFunction -> addFunction(generate(value))
      is KtRecord -> addType(generate(value))
      is KtResource -> addType(generate(value))
      is KtTypeAlias -> addType(generate(value))
      is KtVariant -> addType(generate(value))
    }
  }

  private fun generate(value: KtRecord) = TypeSpec.classBuilder(value.type.simpleName)
    .addModifiers(KModifier.DATA)
    .setDeclaration(value)
    .apply {
      val constructorBuilder = FunSpec.constructorBuilder()

      for (field in value.fields) {
        val name = field.name
        val parameter = ParameterSpec.builder(name, field.type)
          .build()
        constructorBuilder.addParameter(parameter)

        addProperty(
          PropertySpec.builder(name, field.type)
            .initializer("%N", parameter)
            .setDeclaration(field)
            .build(),
        )
      }

      primaryConstructor(constructorBuilder.build())
    }
    .build()

  private fun generate(value: KtResource) = TypeSpec.interfaceBuilder(value.type.simpleName)
    .setDeclaration(value)
    .apply {
      for (function in value.functions) {
        addFunction(generate(function))
      }
    }
    .build()

  private fun generate(value: KtVariant) = TypeSpec.interfaceBuilder(value.type.simpleName)
    .addModifiers(KModifier.SEALED)
    .setDeclaration(value)
    .apply {
      for (case in value.cases) {
        val type = case.type
        if (type != null) {
          addType(
            TypeSpec.classBuilder(case.name)
              .addModifiers(KModifier.DATA)
              .addSuperinterface(value.type)
              .primaryConstructor(
                FunSpec.constructorBuilder()
                  .addParameter("value", case.type)
                  .build(),
              )
              .addProperty(
                PropertySpec.builder("value", case.type)
                  .initializer("%N", "value")
                  .build(),
              )
              .setDeclaration(case)
              .build(),
          )
        } else {
          addType(
            TypeSpec.objectBuilder(case.name)
              .addModifiers(KModifier.DATA)
              .addSuperinterface(value.type)
              .setDeclaration(case)
              .build(),
          )
        }
      }
    }
    .build()

  private fun generate(value: KtEnum) = TypeSpec.enumBuilder(value.type.simpleName)
    .setDeclaration(value)
    .apply {
      for (case in value.cases) {
        addEnumConstant(
          case.name,
          TypeSpec.anonymousClassBuilder()
            .setDeclaration(case)
            .build(),
        )
      }
    }
    .build()

  private fun generate(value: KtTypeAlias) = TypeSpec.classBuilder(value.type.simpleName)
    .addModifiers(KModifier.VALUE)
    .addAnnotation(JvmInline::class)
    .setDeclaration(value)
    .apply {
      val parameter = ParameterSpec.builder("value", value.target)
        .build()

      primaryConstructor(
        FunSpec.constructorBuilder()
          .addParameter(parameter)
          .build(),
      )

      addProperty(
        PropertySpec.builder("value", value.target)
          .initializer("%N", parameter)
          .build(),
      )
    }
    .build()

  private fun generate(value: KtFlags) = TypeSpec.classBuilder(value.type.simpleName)
    .addModifiers(KModifier.DATA)
    .setDeclaration(value)
    .apply {
      val constructorBuilder = FunSpec.constructorBuilder()

      for (field in value.flags) {
        val parameter = ParameterSpec.builder(field.name, BOOLEAN)
          .build()
        constructorBuilder.addParameter(parameter)
        addProperty(
          PropertySpec.builder(field.name, BOOLEAN)
            .initializer("%N", parameter)
            .setDeclaration(field)
            .build(),
        )
      }

      primaryConstructor(constructorBuilder.build())
    }
    .build()

  private fun generate(value: KtFunction) = FunSpec.builder(value.name)
    .addModifiers(KModifier.ABSTRACT)
    .setDeclaration(value)
    .apply {
      for (parameter in value.parameters) {
        addParameter(parameter.name, parameter.type)
      }
      val returnType = value.returnType
      if (returnType != null) {
        returns(returnType)
      }
    }
    .build()

  private fun generate(value: KtWorld) = TypeSpec.objectBuilder(value.type.simpleName)
    .setDeclaration(value)
    .apply {
      for (item in value.items) {
        addWorldItem(item)
      }

      val guest = value.guest
      if (guest != null && guest.apis.isNotEmpty()) {
        addType(
          TypeSpec.interfaceBuilder(guest.type)
            .apply {
              for (export in guest.apis) {
                addWorldApi(export)
              }
            }
            .build(),
        )
      }
      val host = value.host
      if (host != null && host.apis.isNotEmpty()) {
        addType(
          TypeSpec.interfaceBuilder(host.type)
            .apply {
              for (import in host.apis) {
                addWorldApi(import)
              }
            }
            .build(),
        )
      }
    }
    .build()

  private fun TypeSpec.Builder.addWorldItem(value: KtWorld.Item) {
    when (value) {
      is KtEnum -> addType(generate(value))
      is KtFlags -> addType(generate(value))
      is KtRecord -> addType(generate(value))
      is KtResource -> addType(generate(value))
      is KtTypeAlias -> addType(generate(value))
      is KtVariant -> addType(generate(value))
      else -> error("unexpected value: $value")
    }
  }

  private fun TypeSpec.Builder.addWorldApi(externalType: KtWorld.Api) {
    when (externalType) {
      is KtExternalApi -> addProperty(externalType.name, externalType.type)
      is KtFunction -> addFunction(generate(externalType))
      is KtInterface -> {
        addProperty(externalType.instanceName, externalType.type)
        addType(generate(externalType))
      }
    }
  }
}
