package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec

class GuestGenerator {
  fun generate(witPackage: KtWitPackage): FileSpec {
    return FileSpec.builder(witPackage.packageName, "Guest")
      .addFileComment("Generated by Brevity. Do not edit.")
      .apply {
        for (declaration in witPackage.items) {
          addPackageItem(declaration)
        }
      }
      .build()
  }

  private fun FileSpec.Builder.addPackageItem(value: KtWitPackage.Item) {
    when (value) {
      is KtInterface -> {}
      is KtWorld -> addWorld(value)
    }
  }

  private fun FileSpec.Builder.addWorld(value: KtWorld) {
    val guest = value.guest ?: return
    if (guest.apis.isEmpty()) return

    addProperty(PropertySpec.builder(guest.name, guest.type)
      .addModifiers(KModifier.LATEINIT)
      .mutable(true)
      .build())

    for (api in guest.apis) {
      when (api) {
        is KtExternalApi -> {}
        is KtFunction -> addFunction(functionToGuest(guest, api))
        is KtInterface -> {} // addType(interfaceToGuest(guest, api))
      }
    }
  }

  private fun interfaceToGuest(guest: KtWorld.Guest, value: KtInterface): TypeSpec {
    TODO()
  }

  private fun functionToGuest(guest: KtWorld.Guest, value: KtFunction): FunSpec {
    return FunSpec.builder(value.ktName)
      .addAnnotation(AnnotationSpec.builder(KotlinWasm.WasmExport)
        .addMember("%S", "${value.name.packageName}#${value.name.abiName}")
        .build())
      .apply {
        addCode("%N.%N(", guest.name, value.ktName)
        for ((index, parameter) in value.parameters.withIndex()) {
          if (index > 0) addCode(", ")
          addParameter(ParameterSpec.builder(parameter.name, parameter.type).build())
        }
        addCode(")")
        if (value.returnType != null) {
          returns(value.returnType)
        }
      }

      .build()
  }
}
