package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec

class GuestGenerator {
  fun generate(witPackage: KtWitPackage): FileSpec {
    return FileSpec.builder(witPackage.packageName, "Guest")
      .addFileComment("Generated by Brevity. Do not edit.")
      .apply {
        for (declaration in witPackage.items) {
          addPackageItem(declaration)
        }
      }
      .build()
  }

  private fun FileSpec.Builder.addPackageItem(value: KtWitPackage.Item) {
    when (value) {
      is KtInterface -> {}
      is KtWorld -> addWorld(value)
    }
  }

  private fun FileSpec.Builder.addWorld(value: KtWorld) {
    if (value.guest.apis.isEmpty()) return

    val guestFieldName = "${value.type.simpleName}_${value.guest.name}"

    addProperty(PropertySpec.builder(guestFieldName, value.guest.type)
      .addModifiers(KModifier.PRIVATE, KModifier.LATEINIT)
      .mutable(true)
      .build())

    addProperty(PropertySpec.builder(value.guest.name, value.guest.type)
      .receiver(value.type)
      .mutable(true)
      .getter(FunSpec.getterBuilder()
        .addCode("return $guestFieldName")
        .build())
      .setter(FunSpec.setterBuilder()
        .addParameter("value", value.guest.type)
        .addCode("%N = %N", guestFieldName, "value")
        .build())
      .build())

    for (api in value.guest.apis) {
      when (api) {
        is KtExternalApi -> {}
        is KtFunction -> addFunction(functionToGuest(guestFieldName, api))
        is KtInterface -> {} // addType(interfaceToGuest(guest, api))
      }
    }
  }

  private fun interfaceToGuest(guest: KtWorld.Guest, value: KtInterface): TypeSpec {
    TODO()
  }

  private fun functionToGuest(
    guestFieldName: String,
    value: KtFunction,
  ): FunSpec {
    return FunSpec.builder("${guestFieldName}_${value.ktName}")
      .addModifiers(KModifier.PRIVATE)
      .addAnnotation(AnnotationSpec.builder(Symbols.KotlinWasm.WasmExport)
        .addMember("%S", "${value.name.packageName}#${value.name.abiName}")
        .build())
      .apply {
        if (value.returnType != null) {
          addCode("return ")
          returns(value.returnType)
        }
        addCode("%N.%N(", guestFieldName, value.ktName)
        for ((index, parameter) in value.parameters.withIndex()) {
          addParameter(ParameterSpec.builder(parameter.name, parameter.type).build())
          if (index > 0) addCode(", ")
          addCode(parameter.name)
        }
        addCode(")")
      }

      .build()
  }
}
