package dev.wasmo.brevity.kotlin.generator

import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.MemberSpecHolder
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.UNIT

class HostGenerator {
  fun generate(witPackage: KtWitPackage): FileSpec {
    return FileSpec.builder(witPackage.packageName, "Host")
      .addFileComment("Generated by Brevity. Do not edit.")
      .apply {
        for (declaration in witPackage.items) {
          addPackageItem(declaration)
        }
      }
      .build()
  }

  private fun FileSpec.Builder.addPackageItem(value: KtWitPackage.Item) {
    when (value) {
      is KtInterface -> {}
      is KtWorld -> addWorld(value)
    }
  }

  private fun FileSpec.Builder.addWorld(value: KtWorld) {
    val guestApis = value.guest.apis
    val hostTypeName = when {
      value.host.apis.isEmpty() -> UNIT
      else -> value.host.type
    }
    val guestType = when {
      value.guest.apis.isEmpty() -> UNIT
      else -> value.guest.type
    }
    val implementationTypeName = value.type.peerClass("${value.type.simpleName}World")
    val implementationGuestTypeName = when {
      value.guest.apis.isEmpty() -> UNIT
      else -> implementationTypeName.nestedClass("Guest")
    }

    addFunction(
      FunSpec.builder("World")
        .receiver(value.type)
        .returns(Symbols.Brevity.World.parameterizedBy(hostTypeName, guestType))
        .addParameter(
          ParameterSpec.builder(
            "hostFactory",
            LambdaTypeName.get(
              parameters = listOf(ParameterSpec.unnamed(guestType)),
              returnType = hostTypeName,
            ),
          ).build(),
        )
        .apply {
          when {
            value.guest.apis.isEmpty() -> {
              addStatement("val %N = %T", "guest", implementationGuestTypeName)
            }

            else -> {
              addStatement("val %N = %T()", "guest", implementationGuestTypeName)
            }
          }
          addStatement("val %N = hostFactory(%N)", "host", "guest")
          addStatement("return %T(%N, %N)", implementationTypeName, "host", "guest")
        }
        .build(),
    )

    val implementationBuilder = TypeSpec.classBuilder(implementationTypeName.simpleName)

    if (guestApis.isNotEmpty()) {
      for (api in guestApis) {
        implementationBuilder.declareGuestTypes(implementationTypeName, api)
      }

      implementationBuilder.addType(
        TypeSpec.classBuilder(implementationGuestTypeName)
          .addSuperinterface(guestType)
          .apply {
            for (api in guestApis) {
              addGuestApi(implementationTypeName, api)
            }
          }
          .build(),
      )
    }

    addType(
      implementationBuilder
        .addModifiers(KModifier.PRIVATE)
        .primaryConstructor(
          FunSpec.constructorBuilder()
            .addParameter(ParameterSpec.builder("host", hostTypeName).build())
            .addParameter(ParameterSpec.builder("guest", implementationGuestTypeName).build())
            .build(),
        )
        .addSuperinterface(Symbols.Brevity.World.parameterizedBy(hostTypeName, guestType))
        .addProperty(
          PropertySpec.builder("host", hostTypeName)
            .addModifiers(KModifier.OVERRIDE)
            .initializer("host")
            .build(),
        )
        .addProperty(
          PropertySpec.builder("guest", implementationGuestTypeName)
            .addModifiers(KModifier.OVERRIDE)
            .initializer("guest")
            .build(),
        )
        .addFunction(
          FunSpec.builder("initExports")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("instance", Symbols.ChicoryRuntime.Instance)
            .apply {
              for (api in guestApis) {
                initExport(api)
              }
            }
            .build(),
        )
        .addFunction(
          FunSpec.builder("initImports")
            .addModifiers(KModifier.OVERRIDE)
            .addParameter("store", Symbols.ChicoryRuntime.Store)
            .build(),
        )
        .build(),
    )
  }

  /** Declares implementations of guest interfaces. */
  private fun TypeSpec.Builder.declareGuestTypes(worldClassName: ClassName, api: KtWorld.Api) {
    when (api) {
      is KtExternalApi -> {
        val type = worldClassName.nestedClass(api.type.simpleName)
        addType(
          TypeSpec.classBuilder(type)
            .addSuperinterface(api.type)
            .apply {
              for (function in api.functions) {
                addGuestFunction(function)
              }
            }
            .build(),
        )
      }

      else -> {}
    }
  }

  /** Adds symbols to the Guest implementation. */
  private fun TypeSpec.Builder.addGuestApi(worldClassName: ClassName, api: KtWorld.Api) {
    when (api) {
      is KtExternalApi -> {
        val type = worldClassName.nestedClass(api.type.simpleName)
        addProperty(
          PropertySpec.builder(api.name, type)
            .addModifiers(KModifier.OVERRIDE)
            .initializer("%T()", type)
            .build(),
        )
      }

      is KtFunction -> addGuestFunction(api)

      is KtInterface -> {}
    }
  }

  private fun MemberSpecHolder.Builder<*>.addGuestFunction(value: KtFunction) {
    addProperty(
      PropertySpec.builder(value.ktName, Symbols.ChicoryRuntime.ExportFunction)
        .addModifiers(KModifier.LATEINIT)
        .mutable(true)
        .build(),
    )

    addFunction(
      FunSpec.builder(value.ktName)
        .addModifiers(KModifier.OVERRIDE)
        .apply {
          addCode("return %N.apply(", value.ktName)
          for ((index, parameter) in value.parameters.withIndex()) {
            if (index > 0) addCode(", ")
            addCode("%N", parameter.name)
            addParameter(parameter.name, parameter.type)
          }
          addCode(")[0]")
        }
        .returns(value.returnType ?: UNIT)
        .build(),
    )
  }

  private fun FunSpec.Builder.initExport(api: KtWorld.Api) {
    when (api) {
      is KtExternalApi -> {
        for (function in api.functions) {
          addStatement(
            "guest.%N.%N = %N.export(%S)", api.name, function.ktName, "instance",
            function.name,
          )
        }
      }

      is KtFunction -> {
        addStatement("guest.%N = %N.export(%S)", api.ktName, "instance", api.name)
      }

      is KtInterface -> {}
    }
  }
}
