target = 'https://wasmo.com/sdk/1'
version = 1
slug = 'pink'

[[resource]]
url = 'assets/maskable-icon.svg'
content_type = 'image/svg+xml'

[[resource]]
url = 'assets/journal.js'
content_type = 'text/javascript'

[[resource]]
url = 'assets/journal.js.map'
content_type = 'application/json'

[[route]]
path = '/assets/**'
resource_path = '/assets/**'

[launcher]
label = 'Pink Journal'
maskable_icon_path = '/assets/maskable-icon.svg'
