target = 'https://wasmo.com/sdk/1'
version = 1

[[external_resource]]
from = '../../admin-web-app/build/dist/js/productionExecutable'
to = '/www/assets'
include = ['**/*.js', '**/*.js.map']

[launcher]
label = 'Journal'
maskable_icon_path = '/assets/maskable-icon.svg'
home_path = '/admin'
