package com.wasmo.hello.server

import okio.Closeable
import wasmo.app.Platform
import wasmo.app.WasmoApp
import wasmo.http.HttpService
import wasmo.sql.SqlDatabase

class HelloWasmoApp(
  private val platform: Platform,
  private val sqlDatabase: SqlDatabase,
) : Closeable, WasmoApp {
  override val httpService: HttpService?
    get() = null

  fun greetAction() = GreetAction(
    clock = platform.clock,
    sqlDatabase = sqlDatabase,
  )

  override suspend fun afterInstall(
    oldVersion: Long,
    newVersion: Long,
  ) {
    sqlDatabase.newConnection().use {
      it.execute(
        """
        |CREATE TABLE Person (
        |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        |  created_at VARCHAR(255) NOT NULL,
        |  name VARCHAR(255) NOT NULL UNIQUE
        |);
        """.trimMargin(),
      )
    }
  }

  override fun close() {
    sqlDatabase.close()
  }
}
