plugins {
  alias(libs.plugins.kotlin.multiplatform)
  alias(libs.plugins.metro)
  id("wasmo-build")
}

wasmoBuild {
  libraryJvm()
}

kotlin {
  sourceSets {
    val jvmMain by getting {
      dependencies {
        implementation(libs.commons.dbcp2)
        implementation(libs.kotlinx.html)
        implementation(libs.kotlinx.io)
        implementation(libs.kotlinx.io.okio)
        implementation(libs.kotlinx.serialization.json)
        implementation(libs.ktor.server.call.logging)
        implementation(libs.ktor.server.config.yaml)
        implementation(libs.ktor.server.core)
        implementation(libs.ktor.server.default.headers)
        implementation(libs.ktor.server.host.common)
        implementation(libs.ktor.server.html.builder)
        implementation(libs.ktor.server.netty)
        implementation(libs.ktor.server.websockets)
        implementation(libs.logback.classic)
        implementation(libs.okhttp)
        implementation(libs.okio)
        implementation(libs.r2dbc)
        implementation(libs.r2dbc.postgresql)
        implementation(libs.sqldelight.jdbc.driver)
        implementation(libs.stripe)
        implementation(project(":apps:hello:server"))
        implementation(project(":host:api"))
        implementation(project(":host:catalog"))
        implementation(project(":host:client:app"))
        implementation(project(":host:client:launcher"))
        implementation(project(":host:framework"))
        implementation(project(":host:logging"))
        implementation(project(":host:routes"))
        implementation(project(":host:server:accounts:api"))
        implementation(project(":host:server:accounts:real"))
        implementation(project(":host:server:calls:api"))
        implementation(project(":host:server:calls:real"))
        implementation(project(":host:server:computers:api"))
        implementation(project(":host:server:computers:real"))
        implementation(project(":host:server:db"))
        implementation(project(":host:server:deployment"))
        implementation(project(":host:server:events:api"))
        implementation(project(":host:server:events:logging"))
        implementation(project(":host:server:identifiers"))
        implementation(project(":host:server:installedapps:api"))
        implementation(project(":host:server:installedapps:real"))
        implementation(project(":host:server:jobs:api"))
        implementation(project(":host:server:jobs:memory"))
        implementation(project(":host:server:objectstore:api"))
        implementation(project(":host:server:objectstore:fs"))
        implementation(project(":host:server:objectstore:s3"))
        implementation(project(":host:server:okhttpclient"))
        implementation(project(":host:server:passkeys:api"))
        implementation(project(":host:server:passkeys:real"))
        implementation(project(":host:server:payments:api"))
        implementation(project(":host:server:payments:stripe"))
        implementation(project(":host:server:sendemail:api"))
        implementation(project(":host:server:sendemail:postmark"))
        implementation(project(":host:server:sql:api"))
        implementation(project(":host:server:sql:jdbc"))
        implementation(project(":host:server:sql:r2dbc"))
        implementation(project(":host:server:website:api"))
        implementation(project(":host:server:website:real"))
        implementation(project(":host:server:wasm:api"))
        implementation(project(":host:server:wasm:jvm"))
        implementation(project(":host:tokens"))
        implementation(project(":identifiers"))
        implementation(project(":platform:api"))
        implementation(project(":platform:packaging"))
      }
    }
  }
}
