target = 'https://wasmo.com/sdk/1'
version = 1
slug = 'journal'

[[external_resource]]
from = '../client/build/dist/js/productionExecutable'
to = '/assets'
include = ['**/*.js', '**/*.js.map']

[[route]]
path = '/assets/**'
resource_path = '/assets/**'

[launcher]
label = 'Journal'
maskable_icon_path = '/assets/maskable-icon.svg'
