target = 'https://wasmo.com/sdk/1'
version = 1
slug = 'files'

[[resource]]
url = 'assets/maskable-icon.svg'

[[route]]
path = '/assets/maskable-icon.svg'
resource_path = '/assets/maskable-icon.svg'

[launcher]
label = 'Files'
maskable_icon_path = '/assets/maskable-icon.svg'
