package com.wasmo.support.wit.kotlin.generator

import assertk.assertThat
import assertk.assertions.isEqualTo
import com.wasmo.support.wit.io.IoWitPackage
import com.wasmo.support.wit.io.toWitFile
import com.wasmo.support.wit.ir.IrMapper
import com.wasmo.support.wit.toPackageName
import kotlin.test.Test
import okio.Path.Companion.toPath

class ApiGeneratorTest {
  @Test
  fun `full interface`() {
    val wasiClocks = IoWitPackage(
      packageName = "wasi:clocks@0.2.12".toPackageName(),
      files = mapOf(
        "clock.wit".toPath() to """
          |package wasi:clocks@0.2.12;
          |
          |/// gets the epoch time
          |@since(version = 0.2.0)
          |interface wall-clock {
          |    /// A time and date in seconds plus nanoseconds.
          |    @since(version = 0.2.0)
          |    record datetime {
          |        /// Since 1970.
          |        seconds: u64,
          |        /// Always less than 1000000000.
          |        nanoseconds: u32,
          |    }
          |
          |    /// Read the current value of the clock.
          |    @since(version = 0.2.0)
          |    now: func() -> datetime;
          |
          |    /// `pollable` represents a single I/O event which may be ready, or not.
          |    resource pollable {
          |        /// Return the readiness of a pollable. This function never blocks.
          |        ready: func() -> bool;
          |    }
          |
          |    /// Lookup error codes.
          |    variant error-code {
          |        /// Access denied.
          |        access-denied,
          |        /// A catch-all.
          |        other(option<string>),
          |    }
          |
          |    /// File or memory access pattern advisory information.
          |    enum advice {
          |        /// No advice.
          |        normal,
          |        /// sequentially from lower to higher.
          |        sequential,
          |    }
          |
          |    /// How paths are resolved.
          |    flags path-flags {
          |        /// Follow the darn things.
          |        symlink-follow,
          |    }
          |
          |    /// You can do both with an epoch.
          |    type instant = datetime;
          |}
          """.trimMargin().toWitFile(),
      ),
    )

    val witPackage = IrMapper(listOf(wasiClocks)).map().single()
    val kotlinPackage = KotlinMapper().mapPackage(witPackage)
    val fileSpec = ApiGenerator().generate(kotlinPackage)

    assertThat(fileSpec.toString()).isEqualTo(
      """
      |// Generated by wit-kotlin-generator. Do not edit.
      |package wit.wasi.clocks.v0_2_12
      |
      |import kotlin.Boolean
      |import kotlin.String
      |import kotlin.UInt
      |import kotlin.ULong
      |import kotlin.jvm.JvmInline
      |
      |/**
      | * gets the epoch time
      | */
      |public interface WallClock {
      |  /**
      |   * Read the current value of the clock.
      |   */
      |  public fun now(): Datetime
      |
      |  /**
      |   * A time and date in seconds plus nanoseconds.
      |   */
      |  public data class Datetime(
      |    /**
      |     * Since 1970.
      |     */
      |    public val seconds: ULong,
      |    /**
      |     * Always less than 1000000000.
      |     */
      |    public val nanoseconds: UInt,
      |  )
      |
      |  /**
      |   * `pollable` represents a single I/O event which may be ready, or not.
      |   */
      |  public interface Pollable {
      |    /**
      |     * Return the readiness of a pollable. This function never blocks.
      |     */
      |    public fun ready(): Boolean
      |  }
      |
      |  /**
      |   * Lookup error codes.
      |   */
      |  public sealed interface ErrorCode {
      |    /**
      |     * Access denied.
      |     */
      |    public data object AccessDenied : ErrorCode
      |
      |    /**
      |     * A catch-all.
      |     */
      |    public data class Other(
      |      public val `value`: String?,
      |    ) : ErrorCode
      |  }
      |
      |  /**
      |   * File or memory access pattern advisory information.
      |   */
      |  public enum class Advice {
      |    /**
      |     * No advice.
      |     */
      |    Normal,
      |    /**
      |     * sequentially from lower to higher.
      |     */
      |    Sequential,
      |  }
      |
      |  /**
      |   * How paths are resolved.
      |   */
      |  public data class PathFlags(
      |    /**
      |     * Follow the darn things.
      |     */
      |    public val symlinkFollow: Boolean,
      |  )
      |
      |  /**
      |   * You can do both with an epoch.
      |   */
      |  @JvmInline
      |  public value class Instant(
      |    public val `value`: Datetime,
      |  )
      |}
      |
      """.trimMargin(),
    )
  }

  @Test
  fun `full world`() {
    val wasiCommand = IoWitPackage(
      packageName = "wasi:cli@0.3.0".toPackageName(),
      files = mapOf(
        "command.wit".toPath() to """
          |package wasi:cli@0.3.0;
          |
          |world command {
          |  include imports;
          |  export run;
          |  export args: func() -> list<string>;
          |  import platform: interface {
          |    log: func(message: string);
          |  }
          |}
          """.trimMargin().toWitFile(),
        "exit.wit".toPath() to """
          |interface exit {
          |  exit: func(status: result);
          |}
          """.trimMargin().toWitFile(),
        "imports.wit".toPath() to """
          |package wasi:cli@0.3.0;
          |
          |world imports {
          |  import exit;
          |}
          """.trimMargin().toWitFile(),
        "run.wit".toPath() to """
          |interface run {
          |  run: async func() -> result;
          |}
          """.trimMargin().toWitFile(),
      ),
    )

    val witPackage = IrMapper(listOf(wasiCommand)).map().single()
    val kotlinPackage = KotlinMapper().mapPackage(witPackage)
    val fileSpec = ApiGenerator().generate(
      witPackage = kotlinPackage,
      worldFilter = { world -> world.type.simpleName == "Command" }
    )

    assertThat(fileSpec.toString()).isEqualTo(
      """
      |// Generated by wit-kotlin-generator. Do not edit.
      |package wit.wasi.cli.v0_3_0
      |
      |import kotlin.Pair
      |import kotlin.String
      |import kotlin.collections.List
      |
      |public object Command {
      |  public interface Guest {
      |    public val run: Run
      |
      |    public fun args(): List<String>
      |  }
      |
      |  public interface Host {
      |    public val platform: Platform
      |
      |    public val exit: Exit
      |
      |    public interface Platform {
      |      public fun log(message: String)
      |    }
      |  }
      |}
      |
      |public interface Exit {
      |  public fun exit(status: Pair<*, *>)
      |}
      |
      |public interface Run {
      |  public fun run(): Pair<*, *>
      |}
      |
      """.trimMargin(),
    )
  }
}
