package com.wasmo.app.db

import app.cash.sqldelight.TransacterImpl
import app.cash.sqldelight.db.AfterVersion
import app.cash.sqldelight.db.QueryResult
import app.cash.sqldelight.db.SqlDriver
import app.cash.sqldelight.db.SqlSchema
import kotlin.Long
import kotlin.Unit
import kotlin.reflect.KClass

internal val KClass<WasmoDb>.schema: SqlSchema<QueryResult.Value<Unit>>
  get() = WasmoDbImpl.Schema

internal fun KClass<WasmoDb>.newInstance(
  driver: SqlDriver,
  AccountAdapter: Account.Adapter,
  ComputerAccessAdapter: ComputerAccess.Adapter,
  ComputerAdapter: Computer.Adapter,
  ComputerAllocationAdapter: ComputerAllocation.Adapter,
  ComputerSpecAdapter: ComputerSpec.Adapter,
  CookieAdapter: Cookie.Adapter,
  InstalledAppAdapter: InstalledApp.Adapter,
  InstalledAppReleaseAdapter: InstalledAppRelease.Adapter,
  InviteAdapter: Invite.Adapter,
  PasskeyAdapter: Passkey.Adapter,
  StripeCustomerAdapter: StripeCustomer.Adapter,
): WasmoDb = WasmoDbImpl(driver, AccountAdapter, ComputerAccessAdapter, ComputerAdapter, ComputerAllocationAdapter, ComputerSpecAdapter, CookieAdapter, InstalledAppAdapter, InstalledAppReleaseAdapter, InviteAdapter, PasskeyAdapter, StripeCustomerAdapter)

private class WasmoDbImpl(
  driver: SqlDriver,
  AccountAdapter: Account.Adapter,
  ComputerAccessAdapter: ComputerAccess.Adapter,
  ComputerAdapter: Computer.Adapter,
  ComputerAllocationAdapter: ComputerAllocation.Adapter,
  ComputerSpecAdapter: ComputerSpec.Adapter,
  CookieAdapter: Cookie.Adapter,
  InstalledAppAdapter: InstalledApp.Adapter,
  InstalledAppReleaseAdapter: InstalledAppRelease.Adapter,
  InviteAdapter: Invite.Adapter,
  PasskeyAdapter: Passkey.Adapter,
  StripeCustomerAdapter: StripeCustomer.Adapter,
) : TransacterImpl(driver),
    WasmoDb {
  override val accountQueries: AccountQueries = AccountQueries(driver, AccountAdapter)

  override val computerQueries: ComputerQueries =
      ComputerQueries(driver, ComputerAdapter, ComputerAccessAdapter)

  override val computerAccessQueries: ComputerAccessQueries =
      ComputerAccessQueries(driver, ComputerAccessAdapter)

  override val computerAllocationQueries: ComputerAllocationQueries =
      ComputerAllocationQueries(driver, ComputerAllocationAdapter)

  override val computerSpecQueries: ComputerSpecQueries =
      ComputerSpecQueries(driver, ComputerSpecAdapter)

  override val cookieQueries: CookieQueries = CookieQueries(driver, CookieAdapter)

  override val installedAppQueries: InstalledAppQueries =
      InstalledAppQueries(driver, InstalledAppAdapter, InstalledAppReleaseAdapter)

  override val installedAppReleaseQueries: InstalledAppReleaseQueries =
      InstalledAppReleaseQueries(driver, InstalledAppReleaseAdapter)

  override val inviteQueries: InviteQueries = InviteQueries(driver, InviteAdapter)

  override val passkeyQueries: PasskeyQueries = PasskeyQueries(driver, PasskeyAdapter)

  override val stripeCustomerQueries: StripeCustomerQueries =
      StripeCustomerQueries(driver, StripeCustomerAdapter)

  public object Schema : SqlSchema<QueryResult.Value<Unit>> {
    override val version: Long
      get() = 12

    override fun create(driver: SqlDriver): QueryResult.Value<Unit> {
      driver.execute(null, """
          |CREATE TABLE Computer (
          |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          |  created_at TIMESTAMPTZ NOT NULL,
          |  version BIGINT NOT NULL,
          |  slug VARCHAR(255) NOT NULL
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE UNIQUE INDEX ComputerSlug ON Computer (
          |  slug
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE TABLE InstalledApp (
          |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          |  installed_at TIMESTAMPTZ NOT NULL,
          |  computer_id BIGINT NOT NULL,
          |  slug VARCHAR(255) NOT NULL,
          |  active BOOLEAN NULL,
          |  version BIGINT NOT NULL,
          |  wasmo_file_address VARCHAR(65535) NOT NULL,
          |  active_release_id BIGINT NULL DEFAULT NULL
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE UNIQUE INDEX InstalledAppComputerIdSlugActive ON InstalledApp (
          |  computer_id,
          |  slug,
          |  active
          |) WHERE active IS NOT NULL
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE TABLE Account (
          |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          |  version INTEGER NOT NULL
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE TABLE Cookie (
          |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          |  created_at TIMESTAMPTZ NOT NULL,
          |  account_id BIGINT NOT NULL,
          |  token VARCHAR(25) UNIQUE NOT NULL,
          |  created_by_user_agent VARCHAR(255) NULL,
          |  created_by_ip VARCHAR(255) NULL
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE INDEX CookieByAccountId ON Cookie (
          |  account_id
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE TABLE Passkey (
          |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          |  created_at TIMESTAMPTZ NOT NULL,
          |  account_id BIGINT NOT NULL,
          |  passkey_id VARCHAR(255) UNIQUE NOT NULL,
          |  aaguid VARCHAR(36) NOT NULL,
          |  created_by_user_agent VARCHAR(255) NULL,
          |  created_by_ip VARCHAR(255) NULL,
          |  registration_record VARCHAR(65535) NOT NULL
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE INDEX PasskeyByAccountId ON Passkey (
          |  account_id
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE TABLE Invite (
          |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          |  created_at TIMESTAMPTZ NOT NULL,
          |  created_by BIGINT NOT NULL,
          |  version INTEGER NOT NULL,
          |  code VARCHAR(25) UNIQUE NOT NULL,
          |  claimed_at TIMESTAMPTZ NULL,
          |  claimed_by BIGINT NULL
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE INDEX InviteByClaimedById ON Invite (
          |  claimed_by
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE TABLE StripeCustomer (
          |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          |  created_at TIMESTAMPTZ NOT NULL,
          |  version INTEGER NOT NULL,
          |  stripe_customer_id VARCHAR(255) UNIQUE NOT NULL,
          |  name VARCHAR(65535) NOT NULL,
          |  email VARCHAR(65535) NOT NULL,
          |  country VARCHAR(255) NOT NULL,
          |  postal_code VARCHAR(255) NOT NULL
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE TABLE ComputerAllocation (
          |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          |  created_at TIMESTAMPTZ NOT NULL,
          |  version INTEGER NOT NULL,
          |  stripe_customer_id BIGINT NOT NULL,
          |  stripe_subscription_id VARCHAR(255) NOT NULL,
          |  computer_id BIGINT NOT NULL,
          |  active_start TIMESTAMPTZ NOT NULL,
          |  active_end TIMESTAMPTZ NOT NULL
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE INDEX ComputerAllocationByStripeSubscriptionIdActiveStart ON ComputerAllocation (
          |  stripe_subscription_id,
          |  active_start
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE INDEX ComputerAllocationByComputerIdActiveStart ON ComputerAllocation (
          |  computer_id,
          |  active_start
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE TABLE ComputerSpec (
          |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          |  created_at TIMESTAMPTZ NOT NULL,
          |  version BIGINT NOT NULL,
          |  account_id BIGINT NOT NULL,
          |  token VARCHAR(25) UNIQUE NOT NULL,
          |  slug VARCHAR(255) NOT NULL,
          |  computer_id BIGINT NULL
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE TABLE ComputerAccess (
          |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          |  created_at TIMESTAMPTZ NOT NULL,
          |  version INTEGER NOT NULL,
          |  computer_id BIGINT NOT NULL,
          |  account_id BIGINT NOT NULL
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE INDEX ComputerAccessByComputerIdAccountId ON ComputerAccess (
          |  computer_id,
          |  account_id
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE INDEX ComputerAccessByAccountIdComputerId ON ComputerAccess (
          |  account_id,
          |  computer_id
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE TABLE InstalledAppRelease (
          |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          |  first_active_at TIMESTAMPTZ NOT NULL,
          |  computer_id BIGINT NOT NULL,
          |  installed_app_id BIGINT NOT NULL,
          |  app_version BIGINT NOT NULL,
          |  app_manifest_data VARCHAR(65535) NOT NULL
          |)
          """.trimMargin(), 0)
      driver.execute(null, """
          |CREATE INDEX InstalledAppReleaseComputerIdInstalledAppId ON InstalledAppRelease (
          |  computer_id,
          |  installed_app_id
          |)
          """.trimMargin(), 0)
      return QueryResult.Unit
    }

    private fun migrateInternal(
      driver: SqlDriver,
      oldVersion: Long,
      newVersion: Long,
    ): QueryResult.Value<Unit> {
      if (oldVersion <= 1 && newVersion > 1) {
        driver.execute(null, """
            |CREATE TABLE Computer (
            |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            |  created_at TIMESTAMPTZ NOT NULL,
            |  version BIGINT NOT NULL,
            |  slug VARCHAR(255) NOT NULL
            |)
            """.trimMargin(), 0)
        driver.execute(null, """
            |CREATE UNIQUE INDEX ComputerSlug ON Computer (
            |  slug
            |)
            """.trimMargin(), 0)
      }
      if (oldVersion <= 2 && newVersion > 2) {
        driver.execute(null, """
            |CREATE TABLE InstalledApp (
            |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            |  installed_at TIMESTAMPTZ NOT NULL,
            |  computer_id BIGINT NOT NULL,
            |  slug VARCHAR(255) NOT NULL,
            |  active BOOLEAN NULL,
            |  version BIGINT NOT NULL,
            |  wasmo_file_address VARCHAR(65535) NOT NULL,
            |  active_release_id BIGINT NULL DEFAULT NULL
            |)
            """.trimMargin(), 0)
        driver.execute(null, """
            |CREATE UNIQUE INDEX InstalledAppComputerIdSlugActive ON InstalledApp (
            |  computer_id,
            |  slug,
            |  active
            |) WHERE active IS NOT NULL
            """.trimMargin(), 0)
      }
      if (oldVersion <= 3 && newVersion > 3) {
        driver.execute(null, """
            |CREATE TABLE Account (
            |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            |  version INTEGER NOT NULL
            |)
            """.trimMargin(), 0)
      }
      if (oldVersion <= 4 && newVersion > 4) {
        driver.execute(null, """
            |CREATE TABLE Cookie (
            |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            |  created_at TIMESTAMPTZ NOT NULL,
            |  account_id BIGINT NOT NULL,
            |  token VARCHAR(25) UNIQUE NOT NULL,
            |  created_by_user_agent VARCHAR(255) NULL,
            |  created_by_ip VARCHAR(255) NULL
            |)
            """.trimMargin(), 0)
        driver.execute(null, """
            |CREATE INDEX CookieByAccountId ON Cookie (
            |  account_id
            |)
            """.trimMargin(), 0)
      }
      if (oldVersion <= 5 && newVersion > 5) {
        driver.execute(null, """
            |CREATE TABLE Passkey (
            |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            |  created_at TIMESTAMPTZ NOT NULL,
            |  account_id BIGINT NOT NULL,
            |  passkey_id VARCHAR(255) UNIQUE NOT NULL,
            |  aaguid VARCHAR(36) NOT NULL,
            |  created_by_user_agent VARCHAR(255) NULL,
            |  created_by_ip VARCHAR(255) NULL,
            |  registration_record VARCHAR(65535) NOT NULL
            |)
            """.trimMargin(), 0)
        driver.execute(null, """
            |CREATE INDEX PasskeyByAccountId ON Passkey (
            |  account_id
            |)
            """.trimMargin(), 0)
      }
      if (oldVersion <= 6 && newVersion > 6) {
        driver.execute(null, """
            |CREATE TABLE Invite (
            |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            |  created_at TIMESTAMPTZ NOT NULL,
            |  created_by BIGINT NOT NULL,
            |  version INTEGER NOT NULL,
            |  code VARCHAR(25) UNIQUE NOT NULL,
            |  claimed_at TIMESTAMPTZ NULL,
            |  claimed_by BIGINT NULL
            |)
            """.trimMargin(), 0)
        driver.execute(null, """
            |CREATE INDEX InviteByClaimedById ON Invite (
            |  claimed_by
            |)
            """.trimMargin(), 0)
      }
      if (oldVersion <= 7 && newVersion > 7) {
        driver.execute(null, """
            |CREATE TABLE StripeCustomer (
            |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            |  created_at TIMESTAMPTZ NOT NULL,
            |  version INTEGER NOT NULL,
            |  stripe_customer_id VARCHAR(255) UNIQUE NOT NULL,
            |  name VARCHAR(65535) NOT NULL,
            |  email VARCHAR(65535) NOT NULL,
            |  country VARCHAR(255) NOT NULL,
            |  postal_code VARCHAR(255) NOT NULL
            |)
            """.trimMargin(), 0)
      }
      if (oldVersion <= 8 && newVersion > 8) {
        driver.execute(null, """
            |CREATE TABLE ComputerAllocation (
            |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            |  created_at TIMESTAMPTZ NOT NULL,
            |  version INTEGER NOT NULL,
            |  stripe_customer_id BIGINT NOT NULL,
            |  stripe_subscription_id VARCHAR(255) NOT NULL,
            |  computer_id BIGINT NOT NULL,
            |  active_start TIMESTAMPTZ NOT NULL,
            |  active_end TIMESTAMPTZ NOT NULL
            |)
            """.trimMargin(), 0)
        driver.execute(null, """
            |CREATE INDEX ComputerAllocationByStripeSubscriptionIdActiveStart ON ComputerAllocation (
            |  stripe_subscription_id,
            |  active_start
            |)
            """.trimMargin(), 0)
        driver.execute(null, """
            |CREATE INDEX ComputerAllocationByComputerIdActiveStart ON ComputerAllocation (
            |  computer_id,
            |  active_start
            |)
            """.trimMargin(), 0)
      }
      if (oldVersion <= 9 && newVersion > 9) {
        driver.execute(null, """
            |CREATE TABLE ComputerSpec (
            |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            |  created_at TIMESTAMPTZ NOT NULL,
            |  version BIGINT NOT NULL,
            |  account_id BIGINT NOT NULL,
            |  token VARCHAR(25) UNIQUE NOT NULL,
            |  slug VARCHAR(255) NOT NULL,
            |  computer_id BIGINT NULL
            |)
            """.trimMargin(), 0)
      }
      if (oldVersion <= 10 && newVersion > 10) {
        driver.execute(null, """
            |CREATE TABLE ComputerAccess (
            |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            |  created_at TIMESTAMPTZ NOT NULL,
            |  version INTEGER NOT NULL,
            |  computer_id BIGINT NOT NULL,
            |  account_id BIGINT NOT NULL
            |)
            """.trimMargin(), 0)
        driver.execute(null, """
            |CREATE INDEX ComputerAccessByComputerIdAccountId ON ComputerAccess (
            |  computer_id,
            |  account_id
            |)
            """.trimMargin(), 0)
        driver.execute(null, """
            |CREATE INDEX ComputerAccessByAccountIdComputerId ON ComputerAccess (
            |  account_id,
            |  computer_id
            |)
            """.trimMargin(), 0)
      }
      if (oldVersion <= 11 && newVersion > 11) {
        driver.execute(null, """
            |CREATE TABLE InstalledAppRelease (
            |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            |  first_active_at TIMESTAMPTZ NOT NULL,
            |  computer_id BIGINT NOT NULL,
            |  installed_app_id BIGINT NOT NULL,
            |  app_version BIGINT NOT NULL,
            |  app_manifest_data VARCHAR(65535) NOT NULL
            |)
            """.trimMargin(), 0)
        driver.execute(null, """
            |CREATE INDEX InstalledAppReleaseComputerIdInstalledAppId ON InstalledAppRelease (
            |  computer_id,
            |  installed_app_id
            |)
            """.trimMargin(), 0)
      }
      return QueryResult.Unit
    }

    override fun migrate(
      driver: SqlDriver,
      oldVersion: Long,
      newVersion: Long,
      vararg callbacks: AfterVersion,
    ): QueryResult.Value<Unit> {
      var lastVersion = oldVersion

      callbacks.filter { it.afterVersion in oldVersion until newVersion }
      .sortedBy { it.afterVersion }
      .forEach { callback ->
        migrateInternal(driver, oldVersion = lastVersion, newVersion = callback.afterVersion + 1)
        callback.block(driver)
        lastVersion = callback.afterVersion + 1
      }

      if (lastVersion < newVersion) {
        migrateInternal(driver, lastVersion, newVersion)
      }
      return QueryResult.Unit
    }
  }
}
