target = 'https://wasmo.com/sdk/1'
version = 1
slug = 'recipes'

[[resource]]
url = 'maskable-icon.svg'

[[route]]
path = '/maskable-icon.svg'
resource_path = '/maskable-icon.svg'

[launcher]
label = 'Recipes'
maskable_icon_path = '/static/maskable-icon.svg'
