# Homelab Postgresql config.
#
# A good reference is here:
# https://github.com/postgres/postgres/blob/master/src/backend/utils/misc/postgresql.conf.sample

listen_addresses = '*'
data_directory = '/wasmo/postgresql/18'
hba_file = '/wasmo/postgresql/18/pg_hba.conf'
ident_file = '/wasmo/postgresql/18/pg_ident.conf'
