@file:OptIn(ExperimentalUuidApi::class)

package com.wasmo.sql.r2dbc

import app.cash.burst.InterceptTest
import assertk.assertThat
import assertk.assertions.isEqualTo
import kotlin.test.Test
import kotlin.time.Instant
import kotlin.uuid.ExperimentalUuidApi
import kotlin.uuid.Uuid
import kotlinx.coroutines.test.runTest
import okio.ByteString.Companion.encodeUtf8
import wasmo.json.JsonLiteral

class R2dbcSqlServiceTest {
  @InterceptTest
  private val tester = R2dbcTester()

  @Test
  fun `read and write all types`() = runTest {
    val database = tester.sqlService.getOrCreate()
    database.newConnection().use { connection ->
      connection.execute(
        """
        CREATE TABLE AllTypes (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          value_bool BOOLEAN,
          value_s32 INTEGER,
          value_s64 BIGINT,
          value_f32 REAL,
          value_f64 DOUBLE PRECISION,
          value_instant TIMESTAMPTZ,
          value_string TEXT,
          value_bytes BYTEA,
          value_uuid UUID,
          value_json JSONB
        )
        """,
      )

      connection.execute(
        """
        INSERT INTO AllTypes (
          value_bool, value_s32, value_s64, value_f32, value_f64,
          value_instant, value_string, value_bytes, value_uuid, value_json
        ) VALUES (
          $1, $2, $3, $4, $5,
          $6, $7, $8, $9, $10
        )
        """,
      ) {
        bindBool(0, true)
        bindS32(1, 1234567890)
        bindS64(2, 1234567890123456789L)
        bindF32(3, 3.4028235E38f)
        bindF64(4, 1.7976931348623157E308)
        bindInstant(5, Instant.parse("2026-02-01T14:00:00Z"))
        bindString(6, "Wasmo!")
        bindBytes(7, "some bytes".encodeUtf8())
        bindUuid(8, Uuid.parse("00000000-0000-4000-8000-000000000000"))
        bindJson(9, JsonLiteral("""{"b": 2, "a": 1}"""))
      }

      val rowIterator = connection.executeQuery(
        """
        SELECT
          value_bool, value_s32, value_s64, value_f32, value_f64,
          value_instant, value_string, value_bytes, value_uuid, value_json
        FROM AllTypes
        """,
      ) {
      }
      rowIterator.use {
        val onlyRow = rowIterator.next()!!
        assertThat(onlyRow.getBool(0)).isEqualTo(true)
        assertThat(onlyRow.getS32(1)).isEqualTo(1234567890)
        assertThat(onlyRow.getS64(2)).isEqualTo(1234567890123456789L)
        assertThat(onlyRow.getF32(3)).isEqualTo(3.4028235E38f)
        assertThat(onlyRow.getF64(4)).isEqualTo(1.7976931348623157E308)
        assertThat(onlyRow.getInstant(5)).isEqualTo(Instant.parse("2026-02-01T14:00:00Z"))
        assertThat(onlyRow.getString(6)).isEqualTo("Wasmo!")
        assertThat(onlyRow.getBytes(7)).isEqualTo("some bytes".encodeUtf8())
        assertThat(onlyRow.getUuid(8)).isEqualTo(Uuid.parse("00000000-0000-4000-8000-000000000000"))
        assertThat(onlyRow.getJson(9)).isEqualTo(JsonLiteral("""{"a": 1, "b": 2}""")) // sorted!
        assertThat(rowIterator.next()).isEqualTo(null)
      }
    }
  }
}
