package dev.wasmo.brevity.kotlin.generator

import assertk.assertThat
import assertk.assertions.isEqualTo
import dev.wasmo.brevity.io.IoWitPackage
import dev.wasmo.brevity.io.toWitFile
import dev.wasmo.brevity.ir.IrMapper
import dev.wasmo.brevity.toPackageName
import kotlin.test.Test
import okio.Path.Companion.toPath

class KotlinGeneratorTest {
  @Test
  fun `full interface`() {
    val ioPackage = IoWitPackage(
      packageName = "wasi:clocks@0.2.12".toPackageName(),
      files = mapOf(
        "clock.wit".toPath() to """
          |package wasi:clocks@0.2.12;
          |
          |/// gets the epoch time
          |@since(version = 0.2.0)
          |interface wall-clock {
          |    /// A time and date in seconds plus nanoseconds.
          |    @since(version = 0.2.0)
          |    record datetime {
          |        /// Since 1970.
          |        seconds: u64,
          |        /// Always less than 1000000000.
          |        nanoseconds: u32,
          |    }
          |
          |    /// Read the current value of the clock.
          |    @since(version = 0.2.0)
          |    now: func() -> datetime;
          |
          |    /// `pollable` represents a single I/O event which may be ready, or not.
          |    resource pollable {
          |        /// Return the readiness of a pollable. This function never blocks.
          |        ready: func() -> bool;
          |    }
          |
          |    /// Lookup error codes.
          |    variant error-code {
          |        /// Access denied.
          |        access-denied,
          |        /// A catch-all.
          |        other(option<string>),
          |    }
          |
          |    /// File or memory access pattern advisory information.
          |    enum advice {
          |        /// No advice.
          |        normal,
          |        /// sequentially from lower to higher.
          |        sequential,
          |    }
          |
          |    /// How paths are resolved.
          |    flags path-flags {
          |        /// Follow the darn things.
          |        symlink-follow,
          |    }
          |
          |    /// You can do both with an epoch.
          |    type instant = datetime;
          |}
          """.trimMargin().toWitFile(),
      ),
    )

    val irPackage = IrMapper(listOf(ioPackage)).map().single()
    val ktPackage = KtMapper().map(irPackage)

    assertThat(ApiGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.clocks.v0_2_12
      |
      |import kotlin.Boolean
      |import kotlin.String
      |import kotlin.UInt
      |import kotlin.ULong
      |import kotlin.jvm.JvmInline
      |
      |/**
      | * gets the epoch time
      | */
      |public interface WallClock {
      |  /**
      |   * Read the current value of the clock.
      |   */
      |  public fun now(): Datetime
      |
      |  /**
      |   * A time and date in seconds plus nanoseconds.
      |   */
      |  public data class Datetime(
      |    /**
      |     * Since 1970.
      |     */
      |    public val seconds: ULong,
      |    /**
      |     * Always less than 1000000000.
      |     */
      |    public val nanoseconds: UInt,
      |  )
      |
      |  /**
      |   * `pollable` represents a single I/O event which may be ready, or not.
      |   */
      |  public interface Pollable {
      |    /**
      |     * Return the readiness of a pollable. This function never blocks.
      |     */
      |    public fun ready(): Boolean
      |  }
      |
      |  /**
      |   * Lookup error codes.
      |   */
      |  public sealed interface ErrorCode {
      |    /**
      |     * Access denied.
      |     */
      |    public data object AccessDenied : ErrorCode
      |
      |    /**
      |     * A catch-all.
      |     */
      |    public data class Other(
      |      public val `value`: String?,
      |    ) : ErrorCode
      |  }
      |
      |  /**
      |   * File or memory access pattern advisory information.
      |   */
      |  public enum class Advice {
      |    /**
      |     * No advice.
      |     */
      |    Normal,
      |    /**
      |     * sequentially from lower to higher.
      |     */
      |    Sequential,
      |  }
      |
      |  /**
      |   * How paths are resolved.
      |   */
      |  public data class PathFlags(
      |    /**
      |     * Follow the darn things.
      |     */
      |    public val symlinkFollow: Boolean,
      |  )
      |
      |  /**
      |   * You can do both with an epoch.
      |   */
      |  @JvmInline
      |  public value class Instant(
      |    public val `value`: Datetime,
      |  )
      |}
      |
      """.trimMargin(),
    )

    assertThat(GuestGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.clocks.v0_2_12
      |
      |
      """.trimMargin()
    )

    assertThat(HostGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.clocks.v0_2_12
      |
      |
      """.trimMargin()
    )
  }

  @Test
  fun `full world`() {
    val ioPackage = IoWitPackage(
      packageName = "wasi:cli@0.3.0".toPackageName(),
      files = mapOf(
        "command.wit".toPath() to """
          |package wasi:cli@0.3.0;
          |
          |world command {
          |  include imports;
          |  export run;
          |  import args: func() -> list<string>;
          |  import platform: interface {
          |    log: func(message: string);
          |  }
          |}
          """.trimMargin().toWitFile(),
        "exit.wit".toPath() to """
          |interface exit {
          |  exit: func(status: result);
          |}
          """.trimMargin().toWitFile(),
        "imports.wit".toPath() to """
          |package wasi:cli@0.3.0;
          |
          |world imports {
          |  import exit;
          |}
          """.trimMargin().toWitFile(),
        "run.wit".toPath() to """
          |interface run {
          |  run: async func() -> result;
          |}
          """.trimMargin().toWitFile(),
      ),
    )

    val irPackage = IrMapper(listOf(ioPackage)).map().single()
    val ktPackage = KtMapper(
      worldFilter = { world -> world.name.name == "command" },
    ).map(irPackage)

    assertThat(ApiGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.cli.v0_3_0
      |
      |import kotlin.Pair
      |import kotlin.String
      |import kotlin.collections.List
      |
      |public object Command {
      |  public interface Guest {
      |    public val run: Run
      |  }
      |
      |  public interface Host {
      |    public val platform: Platform
      |
      |    public val exit: Exit
      |
      |    public fun args(): List<String>
      |
      |    public interface Platform {
      |      public fun log(message: String)
      |    }
      |  }
      |}
      |
      |public interface Exit {
      |  public fun exit(status: Pair<*, *>)
      |}
      |
      |public interface Run {
      |  public fun run(): Pair<*, *>
      |}
      |
      """.trimMargin(),
    )

    assertThat(GuestGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.cli.v0_3_0
      |
      |import kotlin.Pair
      |import kotlin.wasm.WasmExport
      |
      |private lateinit var Command_guest: Command.Guest
      |
      |public var Command.guest: Command.Guest
      |  get() = Command_guest
      |  set(`value`) {
      |    Command_guest = `value`
      |  }
      |
      |@WasmExport("wasi:cli/run@0.3.0#run")
      |private fun Command_guest_run(): Pair<*, *> = Command_guest.run.run()
      |
      """.trimMargin()
    )

    assertThat(HostGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.cli.v0_3_0
      |
      |import com.dylibso.chicory.runtime.ExportFunction
      |import com.dylibso.chicory.runtime.Instance
      |import com.dylibso.chicory.runtime.Store
      |import dev.wasmo.brevity.World
      |import kotlin.Pair
      |
      |public fun Command.World(hostFactory: (Command.Guest) -> Command.Host): World<Command.Host, Command.Guest> {
      |  val guest = CommandWorld.Guest()
      |  val host = hostFactory(guest)
      |  return CommandWorld(host, guest)
      |}
      |
      |private class CommandWorld(
      |  override val host: Command.Host,
      |  override val guest: Guest,
      |) : World<Command.Host, Command.Guest> {
      |  override fun initExports(instance: Instance) {
      |    guest.run.run = instance.export("wasi:cli/run@0.3.0#run")
      |  }
      |
      |  override fun initImports(store: Store) {
      |  }
      |
      |  public class Run : wit.wasi.cli.v0_3_0.Run {
      |    public lateinit var run: ExportFunction
      |
      |    override fun run(): Pair<*, *> = run.apply()[0]
      |  }
      |
      |  public class Guest : Command.Guest {
      |    override val run: Run = Run()
      |  }
      |}
      |
      """.trimMargin()
    )
  }

  @Test
  fun `world function`() {
    val ioPackage = IoWitPackage(
      packageName = "wasi:cli@0.3.0".toPackageName(),
      files = mapOf(
        "command.wit".toPath() to """
          |world command {
          |  export run: func(args: list<string>) -> s32;
          |}
          """.trimMargin().toWitFile(),
      ),
    )

    val irPackage = IrMapper(listOf(ioPackage)).map().single()
    val ktPackage = KtMapper(
      worldFilter = { world -> world.name.name == "command" },
    ).map(irPackage)

    assertThat(ApiGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.cli.v0_3_0
      |
      |import kotlin.Int
      |import kotlin.String
      |import kotlin.collections.List
      |
      |public object Command {
      |  public interface Guest {
      |    public fun run(args: List<String>): Int
      |  }
      |}
      |
      """.trimMargin(),
    )

    assertThat(GuestGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.cli.v0_3_0
      |
      |import kotlin.Int
      |import kotlin.String
      |import kotlin.collections.List
      |import kotlin.wasm.WasmExport
      |
      |private lateinit var Command_guest: Command.Guest
      |
      |public var Command.guest: Command.Guest
      |  get() = Command_guest
      |  set(`value`) {
      |    Command_guest = `value`
      |  }
      |
      |@WasmExport("run")
      |private fun Command_guest_run(args: List<String>): Int = Command_guest.run(args)
      |
      """.trimMargin()
    )

    assertThat(HostGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.cli.v0_3_0
      |
      |import com.dylibso.chicory.runtime.ExportFunction
      |import com.dylibso.chicory.runtime.Instance
      |import com.dylibso.chicory.runtime.Store
      |import dev.wasmo.brevity.World
      |import kotlin.Int
      |import kotlin.String
      |import kotlin.Unit
      |import kotlin.collections.List
      |
      |public fun Command.World(hostFactory: (Command.Guest) -> Unit): World<Unit, Command.Guest> {
      |  val guest = CommandWorld.Guest()
      |  val host = hostFactory(guest)
      |  return CommandWorld(host, guest)
      |}
      |
      |private class CommandWorld(
      |  override val host: Unit,
      |  override val guest: Guest,
      |) : World<Unit, Command.Guest> {
      |  override fun initExports(instance: Instance) {
      |    guest.run = instance.export("run")
      |  }
      |
      |  override fun initImports(store: Store) {
      |  }
      |
      |  public class Guest : Command.Guest {
      |    public lateinit var run: ExportFunction
      |
      |    override fun run(args: List<String>): Int = run.apply(args)[0]
      |  }
      |}
      |
      """.trimMargin()
    )
  }

  /** We had a bug where we used the wrong package name when following includes across packages. */
  @Test
  fun `imports across packages`() {
    val cliPackage = IoWitPackage(
      packageName = "wasi:cli@0.3.0".toPackageName(),
      files = mapOf(
        "command.wit".toPath() to """
          |package wasi:cli@0.3.0;
          |
          |world command {
          |  import wasi:clocks/monotonic-clock@0.3.0;
          |}
          """.trimMargin().toWitFile(),
      ),
    )
    val clockPackage = IoWitPackage(
      packageName = "wasi:clocks@0.3.0".toPackageName(),
      files = mapOf(
        "clock.wit".toPath() to """
          |package wasi:clocks@0.3.0;
          |
          |interface monotonic-clock {
          |  now: func() -> s64;
          |}
          """.trimMargin().toWitFile(),
      ),
    )

    val irPackages = IrMapper(listOf(cliPackage, clockPackage)).map()
    val ktPackages = irPackages.map(KtMapper()::map)
    val ktPackage = ktPackages.single { it.packageName == "wit.wasi.cli.v0_3_0" }

    assertThat(ApiGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.cli.v0_3_0
      |
      |import wit.wasi.clocks.v0_3_0.MonotonicClock
      |
      |public object Command {
      |  public interface Host {
      |    public val monotonicClock: MonotonicClock
      |  }
      |}
      |
      """.trimMargin(),
    )

    assertThat(GuestGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.cli.v0_3_0
      |
      |
      """.trimMargin()
    )

    assertThat(HostGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.cli.v0_3_0
      |
      |import com.dylibso.chicory.runtime.Instance
      |import com.dylibso.chicory.runtime.Store
      |import dev.wasmo.brevity.World
      |import kotlin.Unit
      |
      |public fun Command.World(hostFactory: (Unit) -> Command.Host): World<Command.Host, Unit> {
      |  val guest = Unit
      |  val host = hostFactory(guest)
      |  return CommandWorld(host, guest)
      |}
      |
      |private class CommandWorld(
      |  override val host: Command.Host,
      |  override val guest: Unit,
      |) : World<Command.Host, Unit> {
      |  override fun initExports(instance: Instance) {
      |  }
      |
      |  override fun initImports(store: Store) {
      |  }
      |}
      |
      """.trimMargin()
    )
  }

  /**
   * Don't declare a property for imported interfaces that don't declare any functions. Otherwise,
   * we may get a collision declaring multiple mutually-redundant `types` members.
   */
  @Test
  fun `imports of interfaces without functions are skipped`() {
    val socketsPackage = IoWitPackage(
      packageName = "wasi:sockets@0.3.0".toPackageName(),
      files = mapOf(
        "sockets.wit".toPath() to """
          |package wasi:sockets@0.3.0;
          |
          |@since(version = 0.3.0)
          |world imports {
          |    @since(version = 0.3.0)
          |    import types;
          |}
          """.trimMargin().toWitFile(),
        "types.wit".toPath() to """
          |interface types {
          |    type ipv4-address = tuple<u8, u8, u8, u8>;
          |    type ipv6-address = tuple<u16, u16, u16, u16, u16, u16, u16, u16>;
          |
          |    variant ip-address {
          |        ipv4(ipv4-address),
          |        ipv6(ipv6-address),
          |    }
          |}
          """.trimMargin().toWitFile(),
      ),
    )

    val irPackages = IrMapper(listOf(socketsPackage)).map()
    val ktPackages = irPackages.map(KtMapper()::map)
    val ktPackage = ktPackages.single()

    assertThat(ApiGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.sockets.v0_3_0
      |
      |import dev.wasmo.brevity.Quad
      |import kotlin.UByte
      |import kotlin.collections.List
      |import kotlin.jvm.JvmInline
      |
      |public object Imports
      |
      |public interface Types {
      |  @JvmInline
      |  public value class Ipv4Address(
      |    public val `value`: Quad<UByte, UByte, UByte, UByte>,
      |  )
      |
      |  @JvmInline
      |  public value class Ipv6Address(
      |    public val `value`: List<*>,
      |  )
      |
      |  public sealed interface IpAddress {
      |    public data class Ipv4(
      |      public val `value`: Ipv4Address,
      |    ) : IpAddress
      |
      |    public data class Ipv6(
      |      public val `value`: Ipv6Address,
      |    ) : IpAddress
      |  }
      |}
      |
      """.trimMargin(),
    )

    assertThat(GuestGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.sockets.v0_3_0
      |
      |
      """.trimMargin()
    )

    assertThat(HostGenerator().generate(ktPackage).toString()).isEqualTo(
      """
      |// Generated by Brevity. Do not edit.
      |package wit.wasi.sockets.v0_3_0
      |
      |import com.dylibso.chicory.runtime.Instance
      |import com.dylibso.chicory.runtime.Store
      |import dev.wasmo.brevity.World
      |import kotlin.Unit
      |
      |public fun Imports.World(hostFactory: (Unit) -> Unit): World<Unit, Unit> {
      |  val guest = Unit
      |  val host = hostFactory(guest)
      |  return ImportsWorld(host, guest)
      |}
      |
      |private class ImportsWorld(
      |  override val host: Unit,
      |  override val guest: Unit,
      |) : World<Unit, Unit> {
      |  override fun initExports(instance: Instance) {
      |  }
      |
      |  override fun initImports(store: Store) {
      |  }
      |}
      |
      """.trimMargin()
    )
  }
}
