/*
 * Copyright (C) 2025 Square, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.wasmo.gradle.domtester

import okio.FileSystem
import okio.Path.Companion.toOkioPath
import okio.Path.Companion.toPath
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFiles
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Write generated-wasmo-dom-tester.js to the current project's karma.config.d directory.
 * (Unfortunately there's no API to tell Karma to load extensions from a build directory.)
 */
internal abstract class WriteSnapshotTestingJsTask : DefaultTask() {
  @get:OutputDirectory
  abstract val karmaConfigD: DirectoryProperty

  @get:InputFiles
  abstract val jvmResources: ConfigurableFileCollection

  @get:Input
  abstract val fullyQualifiedProjectDirectory: Property<String>

  @TaskAction
  fun task() {
    val sourcePath = "/com/wasmo/gradle/domtester/generated-wasmo-dom-tester.js".toPath()
    val targetPath = karmaConfigD.file("generated-wasmo-dom-tester.js")
      .get().asFile.toOkioPath()

    FileSystem.SYSTEM.createDirectories(targetPath.parent!!)
    FileSystem.SYSTEM.write(targetPath) {
      writeUtf8(
        """
        |// DO NOT EDIT.
        |//
        |// This file is generated by the dom-tester plugin. You may ignore it
        |// by adding this line to your .gitignore:
        |//
        |// generated-wasmo-dom-tester.js
        |//
        |
        """.trimMargin(),
      )
      FileSystem.RESOURCES.source(sourcePath).use {
        writeAll(it)
      }
      writeUtf8(
        """
        |
        |installSnapshotsStore(config, "${fullyQualifiedProjectDirectory.get()}");
        |configureMochaTimeout(config, "10s");
        |
        |""".trimMargin(),
      )

      // This combination of features clumsily gets Karma to serve an arbitrary directory at
      // /static/, which is what our web server does.
      for (file in jvmResources.files) {
        writeUtf8(
          """
          |config.files.push(
          |  {
          |    pattern: '${file}/static/**/*',
          |    watched: false,
          |    included: false,
          |    served: true,
          |    nocache: false
          |  }
          |);
          |
          |config.proxies = {
          |  "/assets/": "${file}/static/assets/"
          |};
          """.trimMargin()
        )
      }
    }
  }
}
