package com.wasmo.installedapps

import app.cash.burst.InterceptTest
import assertk.assertThat
import assertk.assertions.isEqualTo
import com.wasmo.testing.apps.MusicApp
import com.wasmo.testing.apps.SnakeApp
import com.wasmo.testing.service.ServiceTester
import kotlin.test.Ignore
import kotlin.test.Test
import kotlinx.coroutines.test.runTest
import wasmo.sql.SqlDatabase

class InstalledAppSqlServiceTest {
  @InterceptTest
  val tester = ServiceTester()

  @Test
  @Ignore("broken")
  fun readAndWriteSql() = runTest {
    val client = tester.newClient()
    val computer = client.createComputer()
    val installedApp = computer.getApp(tester.sampleApps.snake.publishedApp)

    val wasmoApp = installedApp.load() as SnakeApp
    val sqlDatabase = wasmoApp.platform.sqlService.getOrCreate()
    sqlDatabase.createKeyValueTable()

    sqlDatabase.putKeyValue("s1e1", "casino")
    sqlDatabase.putKeyValue("s1e2", "subway")

    assertThat(sqlDatabase.getValue("s1e1")).isEqualTo("casino")
    assertThat(sqlDatabase.getValue("s1e2")).isEqualTo("subway")
  }

  @Test
  @Ignore("not implemented yet")
  fun independentAppsHaveIndependentStores() = runTest {
    val client = tester.newClient()
    val computer = client.createComputer()

    val installedApp1 = computer.getApp(tester.sampleApps.snake.publishedApp)
    val wasmoApp1 = installedApp1.load() as SnakeApp
    val sqlDatabase1 = wasmoApp1.platform.sqlService.getOrCreate()
    sqlDatabase1.createKeyValueTable()

    val installedApp2 = computer.getApp(tester.sampleApps.music.publishedApp)
    val wasmoApp2 = installedApp2.load() as MusicApp
    val sqlDatabase2 = wasmoApp2.platform.sqlService.getOrCreate()
    sqlDatabase2.createKeyValueTable()

    sqlDatabase1.putKeyValue("data", "snake high score")
    sqlDatabase2.putKeyValue("data", "music playlist")

    assertThat(sqlDatabase1.getValue("data")).isEqualTo("snake high score")
    assertThat(sqlDatabase2.getValue("data")).isEqualTo("music playlist")
  }

  @Test
  @Ignore("not implemented yet")
  fun independentComputersHaveIndependentStores() = runTest {
    val client = tester.newClient()

    val computer1 = client.createComputer()
    val installedApp1 = computer1.getApp(tester.sampleApps.snake.publishedApp)
    val wasmoApp1 = installedApp1.load() as SnakeApp
    val sqlDatabase1 = wasmoApp1.platform.sqlService.getOrCreate()
    sqlDatabase1.createKeyValueTable()

    val computer2 = client.createComputer()
    val installedApp2 = computer2.getApp(tester.sampleApps.snake.publishedApp)
    val wasmoApp2 = installedApp2.load() as SnakeApp
    val sqlDatabase2 = wasmoApp2.platform.sqlService.getOrCreate()
    sqlDatabase2.createKeyValueTable()

    sqlDatabase1.putKeyValue("data", "snake high score on computer 1 is 500")
    sqlDatabase2.putKeyValue("data", "snake high score on computer 2 is 900")

    assertThat(sqlDatabase1.getValue("data")).isEqualTo("snake high score on computer 1 is 500")
    assertThat(sqlDatabase2.getValue("data")).isEqualTo("snake high score on computer 2 is 900")
  }

  private suspend fun SqlDatabase.createKeyValueTable() {
    newConnection().use { connection ->
      connection.execute(
        """
        |CREATE TABLE KeyValue (
        |  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        |  key VARCHAR(255) NOT NULL,
        |  value VARCHAR(255) NOT NULL
        |)
        """.trimMargin(),
      )
    }
  }

  private suspend fun SqlDatabase.putKeyValue(key: String, value: String) {
    newConnection().use { connection ->
      connection.execute(
        sql = """
          |INSERT INTO KeyValue(
          |  key,
          |  value
          |)
          |VALUES (
          |  $1,
          |  $2
          |)
          """.trimMargin(),
        bindParameters = {
          bindString(0, key)
          bindString(1, value)
        },
      )
    }
  }

  private suspend fun SqlDatabase.getValue(key: String): String? {
    return newConnection().use { connection ->
      connection.executeQuery(
        sql = """
          |SELECT value FROM KeyValue WHERE key = $1
          """.trimMargin(),
        bindParameters = {
          bindString(0, key)
        },
      ).use { rowIterator ->
        rowIterator.next()?.getString(0)
      }
    }
  }
}
